import { mkdir, readFile, writeFile } from "node:fs/promises";
import sharp from "sharp";
import { readDictionaries } from "./locale-files.mjs";

const dictionaries = await readDictionaries();
if (process.argv.includes("--check")) {
  console.log(`Validated ${Object.keys(dictionaries).join(", ")}`);
} else {
  await Promise.all(
    ["src/i18n/generated", "public/og"].map((p) =>
      mkdir(p, { recursive: true }),
    ),
  );
  const profile = JSON.parse(await readFile("src/data/profile.json", "utf8"));
  const locales = [
    "fr",
    ...Object.keys(dictionaries).filter((locale) => locale !== "fr"),
  ];
  const options = locales.map((code) => ({
    code,
    ...dictionaries[code].locale,
  }));
  const banner = "// Generated by scripts/prepare-locales.mjs. Do not edit.\n";
  await writeFile(
    "src/i18n/generated/locales.ts",
    banner +
      `export const locales: string[] = ${JSON.stringify(locales)};\nexport const localeOptions = ${JSON.stringify(options)};\n`,
  );
  await writeFile(
    "src/i18n/generated/messages.ts",
    banner +
      'import type { Messages } from "../messages";\n' +
      "const loaders: Record<string, () => Promise<Messages>> = {\n" +
      locales
        .map(
          (l) =>
            `${JSON.stringify(l)}: () => import("../../../messages/${l}.json").then(m => m.default),`,
        )
        .join("\n") +
      '\n};\nexport async function loadMessages(locale: string): Promise<Messages> {\nconst loader=loaders[locale];\nif(!loader) throw new Error("Unsupported locale: "+locale);\nreturn loader();\n}\n',
  );
  const xml = (s) =>
    s
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;");
  for (const [locale, m] of Object.entries(dictionaries)) {
    const titleSize = Math.min(
      42,
      Math.floor(1000 / (m.common.role.length * 0.53)),
    );
    const subtitleSize = Math.min(
      27,
      Math.floor(1000 / (m.sharing.availability.length * 0.55)),
    );
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
      <rect width="1200" height="630" fill="#18181b"/><circle cx="1090" cy="110" r="22" fill="#f4a460"/>
      <g font-family="Segoe UI, Arial, sans-serif">
      <text x="80" y="118" font-size="26" fill="#d4d4d8">${xml(m.common.location)}</text>
      <text x="76" y="263" font-size="84" font-weight="600" fill="#fafafa">${xml(profile.name)}<tspan fill="#f4a460">.</tspan></text>
      <text x="80" y="345" font-size="${titleSize}" fill="#fafafa">${xml(m.common.role)}</text>
      <text x="80" y="410" font-size="${subtitleSize}" fill="#d4d4d8">${xml(m.sharing.availability)}</text>
      <path d="M80 484H1120" stroke="#52525b"/>
      <text x="80" y="548" font-size="25" fill="#f4a460">simonfontaine.com</text>
      <text x="785" y="548" font-size="25" fill="#d4d4d8">TypeScript · React · Node.js</text>
      </g></svg>`;
    await sharp(Buffer.from(svg)).png().toFile(`public/og/${locale}.png`);
  }
  console.log(`Prepared ${locales.join(", ")}`);
}
